# Generated by Django 5.2.4 on 2025-08-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='warnings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='public_type',
            field=models.CharField(choices=[('tout_public', 'Tout Public'), ('young_adult', 'Young Adult'), ('adulte', 'Adulte')], max_length=20),
        ),
    ]
