# Generated by Django 5.2.4 on 2025-08-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
