# Generated by Django 5.2.4 on 2025-08-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptercomment',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
