# Generated by Django 5.2.4 on 2025-09-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_character_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slogan',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='sexe',
            field=models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme'), ('autre', 'Autre')], max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='species',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
