# Generated by Django 5.2.4 on 2025-09-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_character_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='addiction',
            new_name='addictions',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='character_trait',
            new_name='character_traits',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='study',
            new_name='studies',
        ),
        migrations.RemoveField(
            model_name='character',
            name='fear',
        ),
        migrations.RemoveField(
            model_name='character',
            name='language',
        ),
        migrations.RemoveField(
            model_name='character',
            name='talent',
        ),
        migrations.AddField(
            model_name='character',
            name='fears',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='languages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='talents',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
