# Generated by Django 5.2.4 on 2025-09-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_addiction_character_addictions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='character_traits',
            new_name='traits',
        ),
    ]
