# Generated by Django 5.2.4 on 2025-09-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_character_traits_character_traits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.TextField(max_length=3000),
        ),
    ]
