# Generated by Django 5.2.4 on 2025-09-10 10:40

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_character_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='creature_images/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='place_images/'),
        ),
    ]
