# Generated by Django 5.2.4 on 2025-09-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_creature_image_alter_place_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='creature',
            name='unique_creature_name_per_book',
        ),
        migrations.RemoveConstraint(
            model_name='place',
            name='unique_place_name_per_book',
        ),
        migrations.AddField(
            model_name='creature',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='creature',
            constraint=models.UniqueConstraint(fields=('book', 'slug'), name='unique_creature_slug_per_book'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('book', 'slug'), name='unique_place_slug_per_book'),
        ),
    ]
