# Generated by Django 5.2.4 on 2025-09-10 15:31

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_creature_unique_creature_name_per_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='creatures/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='place/'),
        ),
    ]
