# Generated by Django 5.2.4 on 2025-09-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_creature_image_alter_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
