# Generated by Django 5.2.4 on 2025-09-18 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_user_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followedauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_authors', to='api.user'),
        ),
        migrations.AlterField(
            model_name='followedauthor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='api.user'),
        ),
    ]
